### ISSUE TITLE
Request : --save option or immediate overwrite

### ISSUE THREAD

**Issue by arcolinuxz** [westandskif/rate-arch-mirrors#2]
Testing it out now like this
rate-arch-mirrors | sudo tee /etc/pacman.d/mirrorlist
that works

having a switch like -d = dry-run nothing saved - I believe that is now when you type rate-arch-mirrors without anything
then you can implement the overwrite like this
if you just type rate-arch-mirrors it will overwrite /etc/pacman.d/mirrorlist - in the end that is what you want
making difficult aliases ... rather not

**Comment by westandskif** [comment]
Hi Erik!
``--save`` totally makes sense, I'll add it.
Next 1-2 weeks are going to be very busy though, so please expect a lull in this.

**Comment by westandskif** [comment]
update:
After discussing this on a forum, I’m convinced that the following way 
```
rate-arch-mirrors | sudo tee /etc/pacman.d/mirrorlist
```
is the right example of use.

It’s built for arch, where sudo is not installed by default, so introducing the option would involve checking multiple options.
While the tool itself doesn’t need root access for the “rate arch mirrors” part.

So it makes sense to leave as is.
