### ISSUE TITLE
Speed test panics when mirrorlist is empty

### ISSUE THREAD

**Issue by JonasVerhofste** [westandskif/rate-arch-mirrors#4]
I tried filtering on only https-only mirrors (`--protocol https`), and noticed that when setting `--entry-country BE`, the speed-test errors out with
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/speed_test.rs:200:26
```

This is probably because the mirrorlist for https in Belgium is empty (which is wrong, but that's a different problem): https://archlinux.org/mirrorlist/?country=BE&protocol=https

My rust is not decent enough to make a PR, but I'd guess a "when !empty" or something needs to be added somewhere.

**Comment by westandskif** [comment]
Thank you, I'll take care of this!
The issue is to be fixed in the next release along with #3

**Comment by JonasVerhofste** [comment]
Thanks for the quick reply! Great tool btw, found some interesting mirrors I never would've thought of testing on my own :)

**Comment by westandskif** [comment]
Hi @JonasVerhofste,
This should be fixed in [v0.3.0](https://github.com/westandskif/rate-arch-mirrors/blob/master/CHANGELOG.md)

**Comment by JonasVerhofste** [comment]
Works like a charm now!

Now to report the https list of BE is wrong, there definitely _are_ https mirrors :p

**Comment by westandskif** [comment]
@JonasVerhofste , cool! glad to hear that :)

p.s. I've checked - [https://archlinux.org/mirrors/](https://archlinux.org/mirrors/) and [https://archlinux.org/mirrorlist/](https://archlinux.org/mirrorlist/), there are only 3 Belgium ones, all of them are http.
The tool queries the official list every time, so once they appear on the list, they'll be speed-tested :)

**Comment by JonasVerhofste** [comment]
I know! What I meant is that the official list is wrong, some are listed as only http, but both mirror.tiguinet.net (which actually has a FR IP, not a BE one. Another error in the list) and archlinux.cu.be are available over https. So I'm gonna have to report those errors somewhere and get the https url's on the list :)
